// FRESH CUT — goofy.js
// THE ODD SIZES. Pop kept these in a different notebook. He never said why.
//
// The joke is SCALE and only scale — everything here is a real thing at an impossible size,
// and every client describes their situation completely deadpan, exactly as Big Stan
// describes his velvet greens. Nobody in this book knows they are being funny. That is the
// whole instrument; do not let anyone make a joke on purpose.
//
// Absurd scale is nearly free: the prop loop already honours `s`, so a gnome at s:9 is a
// three-storey gnome and a tree at s:0.16 is a model railway shrub.
export const GOOFY = [
  {
    id: 'enlarged', block: 6, goofy: true, name: 'Six Hillcrest (Enlarged)', client: 'The Petersons', who: 'DENISE P.', gearLock: 'titan',
    blurb: "An ordinary front lawn. The Petersons are very clear about this. It is an ordinary front lawn and they would appreciate it if you did not make a thing of it. The daisies are four metres tall. It is an ordinary front lawn.",
    pop: 'ordinary, they insist',
    lot: { w: 36, h: 26 }, seed: 701, fence: 'picket', gate: { x: 17, w: 2.4 }, hood: 'giant',
    hero: [{ k: 'can', x: 34, z: -30, s: 0.9, c: 0x4f7a52 }, { k: 'gnome', x: -36, z: -24, s: 1.0 }],
    palette: { sky: 0xffd6ec, fog: 0xffc9e2, hemi: 0xffe0f0, sun: 0xfff3d0, hemiI: 1.05, fogNear: 40, fogFar: 190 },
    terrain: { features: [{ k: 'mound', x: 18, z: 13, r: 15, h: 1.1 }] },
    tiers: [{ t: 'base', tier: 3 }, { t: 'rect', x: 10, z: 9, w: 16, h: 9, tier: 4 }],
    props: [
      { k: 'gnome', x: 6, z: 6, o: { s: 9 } }, { k: 'gnome', x: 30, z: 20, o: { s: 7 }, rot: 2.1 },
      { k: 'birdbath', x: 18, z: 5, s: 5 }, { k: 'mailbox', x: 3, z: 3, s: 6 },
      { k: 'flowerbed', x: 8, z: 20, s: 4.5 }, { k: 'flowerbed', x: 28, z: 8, s: 4 },
      { k: 'kiddiepool', x: 25, z: 18, s: 3.2 }, { k: 'bench', x: 18, z: 23, s: 4.5, rot: 3.14 },
    ],
    zones: [
      { x: 0, z: 0, w: 18, h: 13, name: 'The Near Half' }, { x: 18, z: 0, w: 18, h: 13, name: 'Under the Daisies' },
      { x: 0, z: 13, w: 18, h: 13, name: 'The Gnome Side' }, { x: 18, z: 13, w: 18, h: 13, name: 'The Far Half' },
    ],
    disc: [{ x: 18.4, z: 13.2, tier: 'story', kind: 'ring', label: 'A wedding ring the size of a dinner plate', text: "Oh thank goodness. Dennis has been very calm about losing it, which is how I knew." },
      { x: 34, z: 24, tier: 'keep', kind: 'coin', label: 'A quarter you cannot lift' }],
    junk: 8,
    texts: {
      arrive: "The Titan's in the shed. You'll want it. Mind the birdbath, it holds four hundred litres and Dennis has already been in it once this month.",
      mid: [{ pct: 55, t: "You're making good time. Ignore the gnome. He's load-bearing." }],
      reply: "Ordinary lawn, beautifully done. We don't know why everyone makes a thing of it either. Same time next month?",
    },
  },
  {
    id: 'shag', block: 6, goofy: true, name: 'The Shag Carpet, 1974', client: 'Estate of H. Brill', who: 'THE EXECUTOR', gearLock: 'hover',
    blurb: "Mr Brill installed avocado shag throughout the sunken lounge in 1974 and it has not been cut since. The executor is selling the house. The estate agent used the word 'meadow.' The estate agent was not being poetic.",
    pop: "the agent said 'meadow'",
    lot: { w: 24, h: 18 }, seed: 702, light: 'weird', fence: 'none', gate: { x: 2, w: 2.0 }, hood: 'indoor',
    hero: [{ k: 'manor', x: -2, z: -30, s: 0.55, c: 0xd4c2c2 }],
    room: { wall: 0x8a5a2f, ceil: 0xe8dfc4, skirt: 0x5f3d1e, glass: 0xd8a23f, h: 7, lamp: 'dome', floor: 0x8a6a4a, edge: 0x5f3d1e, lampC: 0xd8823f, door: 0x7a4a33, doorPanel: 0x633c28, curtain: 0xc4a05e, pics: 4, picC: [0x6f4a30, 0x8a6a4a], picInk: 0xd8c9a8,
        furn: [{ k: 'sideboard', x: 8, z: 20.2, rot: 3.1416 }, { k: 'tv', x: 25.6, z: 6.5, rot: -1.5708 },
          { k: 'armchair', x: 25.3, z: 12.5, rot: -1.5708 }, { k: 'armchair', x: -1.4, z: 13.5, rot: 1.5708 },
          { k: 'shelf', x: 16, z: 20.4, rot: 3.1416 }],
    },
    palette: { sky: 0x8a5a2f, fog: 0x6b4a2a, hemi: 0xd8a45c, ground: 0x4a7a3a, sun: 0xffd79a, hemiI: 1.0, sunI: 1.1, fogNear: 26, fogFar: 90 },
    terrain: { features: [{ k: 'bowl', x: 12, z: 9, r: 8, h: 1.2 }] },
    tiers: [{ t: 'base', tier: 4 }, { t: 'rect', x: 8, z: 6, w: 8, h: 6, tier: 3 }],
    props: [
      { k: 'chair', x: 4, z: 4, s: 2.4, rot: 0.6 }, { k: 'chair', x: 20, z: 5, s: 2.4, rot: -0.9 },
      { k: 'planter', x: 12, z: 2.6, s: 3 }, { k: 'acunit', x: 22, z: 15.5, rot: 1.2 },
      { k: 'bench', x: 12, z: 15.6, s: 2.6, rot: 3.14 }, { k: 'shrub', x: 3, z: 15, s: 2.2 },
    ],
    zones: [
      { x: 0, z: 0, w: 12, h: 9, name: 'By the Record Player' }, { x: 12, z: 0, w: 12, h: 9, name: 'The Conversation Pit' },
      { x: 0, z: 9, w: 12, h: 9, name: 'Under the Coffee Table' }, { x: 12, z: 9, w: 12, h: 9, name: 'Toward the Patio Doors' },
    ],
    disc: [{ x: 12.6, z: 9.4, tier: 'story', kind: 'coin', label: 'Eleven dollars in coins, all of it 1970s', text: "That would be the sofa's. Mr Brill said the sofa ate money and we all thought he was being difficult." },
      { x: 22.4, z: 2.2, tier: 'keep', kind: 'ball', label: 'A cocktail olive, fossilised, still speared' }],
    junk: 12,
    texts: {
      arrive: "Hover mower, please — the floorboards are original. The sunken part is deeper than it looks. Everything down there is also avocado.",
      mid: [{ pct: 60, t: "You've found the pit. Yes, it's a whole room. Yes, the carpet goes up the walls a bit. We're not discussing it." }],
      reply: "The agent has changed the listing from 'meadow' to 'feature flooring.' Mr Brill would have been thrilled. Genuinely, he loved that carpet.",
    },
  },
  {
    id: 'model', block: 6, goofy: true, name: 'The Model Railway Club', client: 'Hazel Park & District MRC', who: 'GORDON', gearLock: 'tweezer',
    blurb: "Forty years of work: a whole town in miniature, laid out on trestles, with real grass because Gordon insists real grass is the only thing that reads as grass. It is now nine inches tall. The village of Little Comberton is somewhere under there.",
    pop: 'Little Comberton is under there',
    lot: { w: 20, h: 14 }, seed: 703, fence: 'rail', gate: { x: 9.5, w: 1.4 }, hood: 'indoor',
    hero: [{ k: 'village', x: 0, z: -26, s: 0.55 }],
    room: { wall: 0x9db9a4, ceil: 0xf0ead6, skirt: 0x4a5f50, glass: 0xcfe4ee, h: 8, lamp: 'strip', floor: 0x9a9384, edge: 0x4a5f50, door: 0x5f7a68, doorPanel: 0x4a6153, curtain: 0x9aae9c, pics: 5, picC: [0x4a5f50, 0x6b7f6a], picInk: 0xf0ead6,
        furn: [{ k: 'trestle', x: 6, z: 16.2, rot: 3.1416, s: 0.95 }, { k: 'trestle', x: 14, z: 16.2, rot: 3.1416, s: 0.95 },
          { k: 'shelf', x: -1.5, z: 10, rot: 1.5708, s: 0.95 }, { k: 'trestle', x: 21.6, z: 7, rot: -1.5708, s: 0.95 },
          { k: 'sideboard', x: 10, z: -1.6, rot: 0, s: 0.9 }],
    },
    palette: { sky: 0x9db9a4, fog: 0x9db9a4, hemi: 0xe0eee4, hemiI: 1.05, fogNear: 34, fogFar: 120 },
    terrain: { features: [{ k: 'mound', x: 6, z: 7, r: 4.5, h: 0.9 }, { k: 'ridge', x1: 0, z1: 10, x2: 20, z2: 10, w: 1.6, h: 0.5 }] },
    tiers: [{ t: 'base', tier: 3 }],
    props: [
      ...[[4, 3], [7, 3.6], [10, 3.2], [13, 4], [16, 3.4]].map(([x, z]) => ({ k: 'shed', x, z, s: 0.34, rot: Math.random() * 0.6 })),
      ...[[3, 12], [6, 12.6], [9, 12.2], [12, 12.8], [15, 12.4], [18, 12]].map(([x, z]) => ({ k: 'tree', x, z, o: { s: 0.16 } })),
      { k: 'flagpole', x: 10, z: 6.4, s: 0.3 }, { k: 'bench', x: 17.6, z: 8, s: 0.3 },
      { k: 'statue', x: 10, z: 8.6, s: 0.35 },
    ],
    zones: [
      { x: 0, z: 0, w: 10, h: 7, name: 'The North Sidings' }, { x: 10, z: 0, w: 10, h: 7, name: 'Little Comberton' },
      { x: 0, z: 7, w: 10, h: 7, name: 'The Viaduct Field' }, { x: 10, z: 7, w: 10, h: 7, name: 'The Branch Line' },
    ],
    disc: [{ x: 10.2, z: 8.2, tier: 'story', kind: 'car', label: 'A locomotive, 00 gauge, still in its box', text: "That's the Duchess. She went missing in 1998 and there was an accusation made, and it was never really taken back. Gordon is going to need a moment." },
      { x: 1.4, z: 13.2, tier: 'keep', kind: 'domino', label: 'A platform bench, tiny, hand-painted' }],
    junk: 9,
    texts: {
      arrive: "Tweezers. And I mean that — the smallest thing you have. Little Comberton has a war memorial and I would rather it stayed.",
      mid: [{ pct: 55, t: "You've cleared the viaduct field. Forty years I've had that viaduct. You're the first person to see it since March." }],
      reply: "The whole layout. The Duchess back in her box. Gordon has had to go and sit in the car park for a bit, which from Gordon is an ovation.",
    },
  },
  {
    id: 'bonsai', block: 6, goofy: true, name: 'The Bonsai Lawn', client: 'Kuroda Nursery', who: 'MRS. KURODA', gearLock: 'tweezer',
    blurb: "A lawn the size of a tea tray, forty-one years old, kept in scale with a maple that is itself only slightly larger than a mug. It has been left three weeks. In bonsai terms Mrs Kuroda describes this as 'a catastrophe, but a recoverable one.'",
    pop: 'a recoverable catastrophe',
    lot: { w: 16, h: 12 }, seed: 704, fence: 'picket', gate: { x: 7.5, w: 1.2 }, hood: 'parkland',
    hero: [{ k: 'pagoda', x: 4, z: -52, s: 1.0 }, { k: 'can', x: -30, z: -22, s: 1.1 }],
    palette: { sky: 0xe8c8d8, fog: 0xdcc0cf, hemi: 0xffe4ee, sun: 0xfff0d8, hemiI: 1.0, fogNear: 30, fogFar: 130 },
    terrain: { features: [{ k: 'mound', x: 8, z: 6, r: 6, h: 0.7 }, { k: 'bowl', x: 12.5, z: 8.5, r: 2.6, h: 0.4 }] },
    tiers: [{ t: 'base', tier: 3 }, { t: 'circle', x: 8, z: 6, r: 3.4, tier: 2 }],
    props: [
      { k: 'tree', x: 5.5, z: 5, o: { s: 0.55 } }, { k: 'pine', x: 11.5, z: 4.4, o: { s: 0.4 } },
      { k: 'statue', x: 8, z: 9.4, s: 0.4 }, { k: 'planter', x: 2.4, z: 2.4, s: 0.7 },
      { k: 'planter', x: 13.6, z: 2.4, s: 0.7 }, { k: 'stump', x: 3.4, z: 9.6, s: 0.5 },
    ],
    zones: [
      { x: 0, z: 0, w: 8, h: 6, name: 'The Maple Side' }, { x: 8, z: 0, w: 8, h: 6, name: 'The Gravel Edge' },
      { x: 0, z: 6, w: 8, h: 6, name: 'The Moss Bank' }, { x: 8, z: 6, w: 8, h: 6, name: 'The Little Pool' },
    ],
    disc: [{ x: 8.2, z: 6.4, tier: 'story', kind: 'ring', label: 'A brass ferrule from a very old pair of shears', text: "My teacher's. She cut this lawn for nineteen years before I did. It is not lost now. Thank you." },
      { x: 14.6, z: 10.8, tier: 'keep', kind: 'fossil', label: 'A pebble, chosen once, on purpose, by somebody' }],
    junk: 5,
    texts: {
      arrive: "Slowly. Everything here is forty-one years old and none of it is in a hurry. If you rush, it will show for a season.",
      mid: [{ pct: 60, t: "Good. You have understood that the moss bank is not a lawn and does not get cut. Most people do not." }],
      reply: "Recovered. Come in spring when the maple turns — it is worth the drive, and I will make tea, and we will not talk about the three weeks.",
    },
  },
  {
    id: 'chessboard', block: 6, goofy: true, name: "The Groundskeeper's Chessboard", client: 'Bellamy House & Gardens', who: 'MRS. ADEYEMI', pattern: true,
    blurb: "Arthur laid out a chessboard in the walled garden in 1979, sixty-four squares, mown alternately. He did it every fortnight for thirty years and never once explained why. The squares are still there, faintly, if you know where to stand.",
    pop: 'sixty-four squares',
    lot: { w: 32, h: 24 }, seed: 705, fence: 'rail', gate: { x: 15.5, w: 1.6 }, hood: 'parkland',
    hero: [{ k: 'manor', x: 0, z: -46, s: 1.0 }, { k: 'chess', x: -26, z: -28, s: 1.0, piece: 'king', c: 0xf4efe2 }, { k: 'chess', x: 28, z: -26, s: 0.9, c: 0x3f3833 }],
    palette: { sky: 0xd9e4ef, fog: 0xc9d6e4, hemi: 0xeef2f8, sun: 0xfffaf0, hemiI: 0.95, fogNear: 44, fogFar: 180 },
    terrain: { features: [{ k: 'mound', x: 16, z: 12, r: 16, h: 0.5 }] },
    tiers: [{ t: 'base', tier: 2 }],
    props: [
      { k: 'statue', x: 2, z: 2, s: 1.4 }, { k: 'statue', x: 30, z: 2, s: 1.4 },
      { k: 'statue', x: 2, z: 22, s: 1.4 }, { k: 'statue', x: 30, z: 22, s: 1.4 },
      { k: 'fountain', x: 16, z: 12 }, { k: 'bench', x: 16, z: 22.4, rot: 3.14 },
      { k: 'planter', x: 8, z: 3 }, { k: 'planter', x: 24, z: 3 },
    ],
    zones: [
      { x: 0, z: 0, w: 32, h: 4, name: 'Rank One' }, { x: 0, z: 4, w: 32, h: 4, name: 'Rank Two' },
      { x: 0, z: 8, w: 32, h: 4, name: 'Rank Three' }, { x: 0, z: 12, w: 32, h: 4, name: 'Rank Four' },
      { x: 0, z: 16, w: 32, h: 4, name: 'Rank Five' }, { x: 0, z: 20, w: 32, h: 4, name: 'Rank Six' },
    ],
    disc: [{ x: 16.6, z: 14.2, tier: 'story', kind: 'domino', label: 'A chess piece: one white bishop, wooden, worn smooth', text: "Arthur played by post with a man in Nairobi for twenty-two years. He kept the board out here. I always assumed it was decorative. It was not decorative." },
      { x: 30.6, z: 21.4, tier: 'keep', kind: 'medal', label: 'A brass plate: A. HOLLOWAY, HEAD GARDENER' }],
    junk: 7,
    texts: {
      arrive: "Alternate every rank. That's all Arthur ever wrote down about it — one line, in a notebook otherwise entirely about drainage.",
      mid: [{ pct: 60, t: "Stand by the fountain and look back. There it is. Thirty years and I never once came out here on the right day." }],
      reply: "Sixty-four squares. We're putting the bishop in the hall with the plate and a very short label. He would have hated the fuss and we're doing it anyway.",
    },
  },
  {
    id: 'felt', block: 6, goofy: true, name: 'The Felt', client: 'Riverside Social Club', who: 'BARRY', gearLock: 'hover',
    blurb: "The club's championship table was left under a leaking skylight for a winter. Something took. Barry describes what is now growing on the felt as 'a difficult green' and has asked you not to say anything to the league.",
    pop: "don't tell the league",
    lot: { w: 26, h: 14 }, seed: 706, fence: 'rail', gate: { x: 12.5, w: 1.4 }, hood: 'indoor',
    hero: [{ k: 'manor', x: 0, z: -26, s: 0.5, c: 0xc9bda8 }],
    room: { wall: 0x2f5b3f, ceil: 0xd9cfae, skirt: 0x7a5a2f, glass: 0xf0e0a8, h: 6.5, lamp: 'shade', floor: 0x6b4a30, edge: 0x7a5a2f, lampC: 0x24462f, doorSide: 'e', door: 0x5e4736, doorPanel: 0x4a3728, curtain: 0x7a5a2f, pics: 3, picC: [0x7a5a2f, 0x5e4736], picInk: 0xe8dfc4,
        furn: [{ k: 'bench', x: 8, z: 16.2, rot: 3.1416, s: 0.9 }, { k: 'bench', x: 18, z: 16.2, rot: 3.1416, s: 0.9 },
          { k: 'shelf', x: -1.5, z: 5, rot: 1.5708, s: 0.9 }, { k: 'sideboard', x: -1.5, z: 10.5, rot: 1.5708, s: 0.9 },
          { k: 'bench', x: 27.6, z: 10.5, rot: -1.5708, s: 0.9 }],
    },
    palette: { sky: 0x2f5b3f, fog: 0x24462f, hemi: 0x7fc79a, ground: 0x2a4a35, sun: 0xffe9b0, hemiI: 0.95, sunI: 1.15, fogNear: 22, fogFar: 80 },
    terrain: { features: [{ k: 'slope', ang: 1.571, h: 0.5 }, { k: 'bowl', x: 13, z: 7, r: 9, h: 0.35 }] },
    tiers: [{ t: 'base', tier: 3 }],
    props: [
      ...[[4, 3.5], [9, 10.5], [17, 4], [21, 9.5], [13, 7], [6, 8]].map(([x, z], i) => ({ k: 'kiddiepool', x, z, s: 0.55, o: { c: [0xc0392b, 0xf2c14e, 0x3b6ea5, 0x4f8f52, 0x8d6a9a, 0xd8823f][i] } })),
      { k: 'holeflag', x: 1.4, z: 1.4, o: { c: 0x2b2b2b } }, { k: 'holeflag', x: 24.6, z: 1.4, o: { c: 0x2b2b2b } },
      { k: 'holeflag', x: 1.4, z: 12.6, o: { c: 0x2b2b2b } }, { k: 'holeflag', x: 24.6, z: 12.6, o: { c: 0x2b2b2b } },
      { k: 'bench', x: 13, z: 13.2, rot: 3.14 },
    ],
    zones: [
      { x: 0, z: 0, w: 13, h: 7, name: 'The Baulk End' }, { x: 13, z: 0, w: 13, h: 7, name: 'The Black Spot End' },
      { x: 0, z: 7, w: 13, h: 7, name: 'The Long Cushion' }, { x: 13, z: 7, w: 13, h: 7, name: 'The Far Pocket' },
    ],
    disc: [{ x: 13.4, z: 7.4, tier: 'story', kind: 'ball', label: 'The black, still where it was left', text: "Frank potted that to win the '89 final and then the roof went and nobody moved it. Nobody. For thirty-six years. I'm not touching it either, put it back." },
      { x: 25.2, z: 13.2, tier: 'keep', kind: 'coin', label: 'A pound coin, chalked, used as a marker' }],
    junk: 8,
    texts: {
      arrive: "Hover, please, the slate's underneath. And Barry — that's me — would consider it a personal kindness if this never came up at the AGM.",
      mid: [{ pct: 55, t: "It's coming back green. Proper green. I might cry, and if I do we're also not mentioning that." }],
      reply: "You can see the spots again. The league will never know. The league will absolutely know by Thursday, but not from us.",
    },
  },
  {
    id: 'doormat', block: 6, goofy: true, name: 'The Welcome Mat', client: '—', who: '—', gearLock: 'titan',
    blurb: "There is a house at the end of the lane with a doormat forty metres across. Nobody has ever seen who lives there. The mat has gone to seed. An envelope of cash arrives every spring and the note says the same three words it has said for eleven years: PLEASE AND THANK YOU.",
    pop: 'please and thank you',
    lot: { w: 40, h: 20 }, seed: 707, light: 'dusk', fence: 'none', gate: { x: 19, w: 3 }, hood: 'giant',
    hero: [{ k: 'door', x: 0, z: -44, s: 1.0 }],
    palette: { sky: 0x6a5a8a, fog: 0x54476e, hemi: 0xb0a0d0, sun: 0xffc98a, hemiI: 0.9, fogNear: 34, fogFar: 150 },
    terrain: { features: [{ k: 'ridge', x1: 0, z1: 3, x2: 40, z2: 3, w: 3, h: 0.8 }, { k: 'ridge', x1: 0, z1: 17, x2: 40, z2: 17, w: 3, h: 0.8 }, { k: 'mound', x: 20, z: 10, r: 18, h: 0.5 }] },
    tiers: [{ t: 'base', tier: 4 }, { t: 'rect', x: 6, z: 6, w: 28, h: 8, tier: 3 }],
    props: [
      { k: 'booth', x: 3, z: 10, s: 3.4, rot: 1.571 }, { k: 'booth', x: 37, z: 10, s: 3.4, rot: -1.571 },
      { k: 'statue', x: 20, z: 2.4, s: 3 },
      { k: 'planter', x: 10, z: 17.6, s: 2.6 }, { k: 'planter', x: 30, z: 17.6, s: 2.6 },
    ],
    zones: [
      { x: 0, z: 0, w: 20, h: 10, name: 'The Left Half of WELCOME' }, { x: 20, z: 0, w: 20, h: 10, name: 'The Right Half of WELCOME' },
      { x: 0, z: 10, w: 20, h: 10, name: 'The Bristles (west)' }, { x: 20, z: 10, w: 20, h: 10, name: 'The Bristles (east)' },
    ],
    disc: [{ x: 20.4, z: 10.6, tier: 'story', kind: 'key', label: 'A house key. It is ordinary sized.', text: "(You look at the door. The door is eleven metres high. You put the key back exactly where you found it, and you do not mention it in the invoice.)" },
      { x: 38.4, z: 18.6, tier: 'keep', kind: 'dogtag', label: 'A luggage label, blank, very old' }],
    junk: 6, noRadio: true,
    texts: {
      arrive: "(The envelope was under a stone by the gate, as always. The Titan is already parked at the edge of the mat, as always. You have never once seen it delivered.)",
      mid: [{ pct: 65, t: "(You can read the W now, from the middle. You had always assumed the pattern was decorative.)" }],
      reply: "(A second envelope, thicker, and the same three words. Eleven years. You have stopped finding it strange, which is possibly the strangest part.)",
    },
  },
  {
    id: 'gnomes', block: 6, goofy: true, name: 'The Gnome Convention', client: 'Midlands Gnome Fanciers', who: 'PATRICIA', gearLock: 'tweezer',
    blurb: "Four hundred and eleven garden gnomes, arranged in rows on a show field, at every size from thumbnail to shed. Judging is Saturday. The grass between them has not been touched since the rows were laid out and Patricia is being very brave about it.",
    pop: 'judging is Saturday',
    lot: { w: 30, h: 22 }, seed: 708, fence: 'picket', gate: { x: 14.5, w: 1.4 }, hood: 'parkland',
    hero: [{ k: 'village', x: 0, z: -40, s: 1.1 }, { k: 'gnome', x: 26, z: -26, s: 1.3 }],
    palette: { sky: 0xcfe8b0, fog: 0xbfdd9e, hemi: 0xe8f5cf, sun: 0xfff6c8, hemiI: 1.1, fogNear: 40, fogFar: 170 },
    terrain: { features: [{ k: 'step', x1: 0, z1: 11, x2: 30, z2: 11, w: 2.4, h: 0.9 }] },
    tiers: [{ t: 'base', tier: 3 }],
    props: [
      ...[3, 7, 11, 15, 19, 23, 27].flatMap((x, i) => [4, 8, 14, 18].map((z, j) => ({
        k: 'gnome', x, z, rot: (i + j) * 0.7, o: { s: [0.4, 0.8, 1.6, 3.2, 5.5][(i + j) % 5] },
      }))),
      { k: 'booth', x: 15, z: 20.6, o: { c: 0x4f8f52 } },
      { k: 'bench', x: 4, z: 20.4, rot: 3.14 }, { k: 'bench', x: 26, z: 20.4, rot: 3.14 },
    ],
    zones: [
      { x: 0, z: 0, w: 15, h: 11, name: 'Rows A–D (Small)' }, { x: 15, z: 0, w: 15, h: 11, name: 'Rows E–H (Medium)' },
      { x: 0, z: 11, w: 15, h: 11, name: 'Rows J–M (Large)' }, { x: 15, z: 11, w: 15, h: 11, name: 'The Open Class' },
    ],
    disc: [{ x: 15.4, z: 11.4, tier: 'story', kind: 'glasses', label: "A tiny pair of spectacles, gnome-scale, hand-made", text: "Those are for Alfred. He's in the Open Class and he has been judged four times without them because I could not find them. Four times, and he still placed." },
      { x: 28.6, z: 1.6, tier: 'keep', kind: 'medal', label: 'A rosette: THIRD, VETERAN CLASS, 1991' }],
    junk: 9,
    texts: {
      arrive: "Between the rows, if you'd be so kind, and please do not turn any of them to face away from the path. They are shown facing the path. It matters.",
      mid: [{ pct: 55, t: "You've done the small rows. I can see Cynthia's from here and she is going to be furious, which is the point of the small rows." }],
      reply: "Four hundred and eleven gnomes on cut grass. Alfred has his spectacles. He placed second and Patricia has described this as 'a robbery, but a lovely day.'",
    },
  },
  {
    id: 'windowsill', block: 6, goofy: true, name: 'The Windowsill', client: 'Apartment 4B', who: 'THEO', gearLock: 'tweezer',
    blurb: "Theo grows wheatgrass in a tray on his kitchen windowsill. The tray is ninety centimetres long. Theo has booked a full lawn service. Theo is entirely serious and has already paid, and when you arrive the ladder is out and the window is open.",
    pop: 'he has already paid',
    lot: { w: 18, h: 10 }, seed: 709, fence: 'rail', gate: { x: 8.5, w: 1.2 }, hood: 'indoor',
    hero: [{ k: 'pagoda', x: 1, z: -34, s: 0.42 }],
    room: { wall: 0xdce8ee, ceil: 0xf4f7f8, skirt: 0x9db4bf, glass: 0xcfe8f2, h: 6, lamp: 'flush', floor: 0xcfd6d8, edge: 0x9db4bf, radiator: false, door: 0xbfcfd8, doorPanel: 0xaebfc9, curtain: 0xe8eef0, pics: 2, picC: [0x9db4bf], picInk: 0xf4f7f8, lampZ: -1,
        furn: [{ k: 'counter', x: 5, z: 12.2, rot: 3.1416, s: 0.85 }, { k: 'counter', x: 12, z: 12.2, rot: 3.1416, s: 0.85 },
          { k: 'fridge', x: 19.7, z: 3.4, rot: -1.5708, s: 0.85 }, { k: 'counter', x: 19.7, z: 7.6, rot: -1.5708, s: 0.85 }],
    },
    palette: { sky: 0xdce8ee, fog: 0xcfe0e8, hemi: 0xf0f7fa, hemiI: 1.1, fogNear: 24, fogFar: 90 },
    terrain: { features: [{ k: 'ridge', x1: 0, z1: 1.6, x2: 18, z2: 1.6, w: 1.8, h: 0.7 }, { k: 'ridge', x1: 0, z1: 8.4, x2: 18, z2: 8.4, w: 1.8, h: 0.7 }] },
    tiers: [{ t: 'base', tier: 4 }],
    props: [
      { k: 'planter', x: 2.4, z: 5, s: 1.6 }, { k: 'planter', x: 15.6, z: 5, s: 1.6 },
      { k: 'acunit', x: 9, z: 9.2, s: 1.2 }, { k: 'chair', x: 9, z: 1.2, s: 0.8, rot: 3.14 },
    ],
    zones: [
      { x: 0, z: 0, w: 9, h: 5, name: 'The Left Half of the Tray' }, { x: 9, z: 0, w: 9, h: 5, name: 'The Right Half of the Tray' },
      { x: 0, z: 5, w: 18, h: 5, name: 'The Front Edge (mind the drop)' },
    ],
    disc: [{ x: 9.2, z: 5.4, tier: 'story', kind: 'ring', label: 'A shirt button, bone, four holes', text: "Off my grandfather's coat. It's been in the tray since I planted it — I put it there on purpose and then forgot I'd done it, which he'd have found very funny." },
      { x: 17, z: 1.2, tier: 'keep', kind: 'coin', label: 'A five-pence piece, standing on its edge in the soil' }],
    junk: 4,
    texts: {
      arrive: "I know. I know. But it IS a lawn, and it does get long, and nobody else would take the booking. Tea's on. Mind the front edge, it's four floors.",
      mid: [{ pct: 60, t: "It already looks better than the actual park across the road, and I want you to know I'm aware of what that says about me." }],
      reply: "Cut, edged, and photographed from above. Theo has framed the before-and-after and hung it in the kitchen, at eye level, where guests cannot avoid it.",
    },
  },
  {
    id: 'twine', block: 6, goofy: true, name: 'The Ball of Twine (Grounds)', client: "Hazel Park's Second-Largest Attraction", who: 'RAY (UTILITIES)', gearLock: 'titan',
    blurb: "The world's second-largest ball of twine sits in a field off Route 9 under a shelter, and the field around it is municipal responsibility, which is to say it is Ray's, which is to say it is now yours. The ball is nine metres across. The grass around it goes uphill in every direction, because the ball made a hill.",
    pop: 'second-largest, and honest about it',
    lot: { w: 34, h: 26 }, seed: 710, fence: 'chain', gate: { x: 16.5, w: 2.2 }, hood: 'openfield',
    hero: [{ k: 'ball', x: 0, z: -38, s: 1.15, lift: 0.32 }],
    palette: { sky: 0xf2c98a, fog: 0xe6b877, hemi: 0xffe8c0, sun: 0xffdca0, hemiI: 1.05, fogNear: 44, fogFar: 190 },
    terrain: { features: [{ k: 'mound', x: 17, z: 13, r: 12, h: 2.6 }, { k: 'ridge', x1: 0, z1: 24, x2: 34, z2: 24, w: 3, h: 0.7 }] },
    tiers: [{ t: 'base', tier: 3 }, { t: 'circle', x: 17, z: 13, r: 5, tier: 2 }],
    props: [
      // ⚠️ NO FOUNTAIN HERE. It was a placeholder for the ball before the hero system, at
      // s: 3.2, and it sat on the summit of the centre mound directly ahead of spawn — the
      // dark mass I mistook for a treeline, then a shelter roof, then the sky itself.
      // Isolation (hide one group, re-sample) pinned it three separate times. Even at 1.0
      // it still owned the middle of the frame and hid the ball. The ball is the landmark.
      { k: 'bench', x: 12.4, z: 15.6, rot: 2.6 },
      { k: 'booth', x: 5, z: 22, rot: 0.5 }, { k: 'bench', x: 17, z: 21.4, rot: 3.14 },
      { k: 'flagpole', x: 29, z: 22 }, { k: 'tyrestack', x: 3.4, z: 4 }, { k: 'tyrestack', x: 30.6, z: 4 },
      { k: 'wheelbarrow', x: 31, z: 24, rot: 2.4 },
    ],
    zones: [
      { x: 0, z: 0, w: 17, h: 13, name: 'The North Slope' }, { x: 17, z: 0, w: 17, h: 13, name: 'The East Slope' },
      { x: 0, z: 13, w: 17, h: 13, name: 'The West Slope' }, { x: 17, z: 13, w: 17, h: 13, name: 'The Car Park Side' },
    ],
    disc: [{ x: 17.6, z: 13.8, tier: 'story', kind: 'photo', label: 'A photo: two men, a smaller ball, 1958', text: "That's Ellis and my uncle the year they started. They knew about the bigger one in Kansas the whole time. They started anyway. I think about that a lot." },
      { x: 32.4, z: 24.6, tier: 'keep', kind: 'arrowhead', label: 'A length of the original twine, in a labelled bag' }],
    junk: 8,
    texts: {
      arrive: "Titan for the slopes. Across, not up. And if a car pulls in while you're working, wave — we get about eleven a year and they've all driven a long way for this.",
      mid: [{ pct: 60, t: "Two cars in. That's a big day. One of them's from out of state and they've been round it twice." }],
      reply: "The whole hill, cut, and you waved at three cars. Second-largest in the world and the best-kept, and Ray would like that noted somewhere official.",
    },
  },
];
